'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3082
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WdicGazer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  CountryCode.txt に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CountryCodeFile() As String
            Get
                Return ResourceManager.GetString("CountryCodeFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  WLF に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DicGroupFileExt() As String
            Get
                Return ResourceManager.GetString("DicGroupFileExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  DV6 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DirectryFileExt() As String
            Get
                Return ResourceManager.GetString("DirectryFileExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  DIR.LST に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DirectryListFile() As String
            Get
                Return ResourceManager.GetString("DirectryListFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  EntityReferences.txt に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property EntityReferncesFile() As String
            Get
                Return ResourceManager.GetString("EntityReferncesFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  EraList.txt に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property EraListFile() As String
            Get
                Return ResourceManager.GetString("EraListFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ErrorMessage.txt に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ErrorMessageFile() As String
            Get
                Return ResourceManager.GetString("ErrorMessageFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  FILE.GL に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GroupFile() As String
            Get
                Return ResourceManager.GetString("GroupFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  LangCode.txt に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property LangCodeFile() As String
            Get
                Return ResourceManager.GetString("LangCodeFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  （なし） に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property NO_ITEM() As String
            Get
                Return ResourceManager.GetString("NO_ITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  PLF に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property PluginGroupFileExt() As String
            Get
                Return ResourceManager.GetString("PluginGroupFileExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  http://www.rfc-editor.org/rfc/ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property RFCEditor() As String
            Get
                Return ResourceManager.GetString("RFCEditor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property RFCEditorDir() As String
            Get
                Return ResourceManager.GetString("RFCEditorDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  http://www.rfc-editor.org/std/ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STDEditorDir() As String
            Get
                Return ResourceManager.GetString("STDEditorDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  default.css に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property StyleSheetFile() As String
            Get
                Return ResourceManager.GetString("StyleSheetFile", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
